### ISSUE TITLE
커버 이미지 없는 경우를 위한 임시 default image

### ISSUE THREAD

**Issue by hou27** [Quickchive/quickchive-backend#108]
문서 크롤링 후 커버 이미지가 없는 경우를 위한 기본 이미지 설정

**Comment by hou27** [comment]
![default_quickchive](https://user-images.githubusercontent.com/65845941/193978184-5f4ee297-715c-484b-9333-d20c082ea6f7.png)

**Comment by hou27** [comment]
이걸로 처리하려 하는데 프론트 asset에 넣어서 처리하는 방식은 어떻게 생각하세요? @oseunghyun

**Comment by oseunghyun** [comment]
@hou27  네 제가 해도 괜찮아요! 
프론트에서도 이미지 없는 경우에 대해서 예외처리 되어 있어서 저 이미지로 변경하기만 하면 될 것 같아요

**Comment by hou27** [comment]
> @hou27 네 제가 해도 괜찮아요! 프론트에서도 이미지 없는 경우에 대해서 예외처리 되어 있어서 저 이미지로 변경하기만 하면 될 것 같아요

넵 감사합니다 ㅎ 완료되면 이슈 닫아주세요!
