### ISSUE TITLE
Test Server 구축

### ISSUE THREAD

**Issue by hou27** [Quickchive/quickchive-backend#129]
현재 배포 서버가 위치한 ec2 인스턴스 내에 test server를 함께 올려볼 예정

**Comment by hou27** [comment]
@oseunghyun 
http://api.hou27.shop:3000/
이 주소로 테스트 서버 배포해뒀습니다!
테스트용 프론트는 이 주소로 api 요청하도록 해주세요

**Comment by oseunghyun** [comment]
@hou27 
변경했는데 https->http라 요청 에러 발생하네요.. 
혹시 https로 변경 가능하신가요!?
<img width="550" alt="스크린샷 2022-11-18 오후 11 33 28" src="https://user-images.githubusercontent.com/73734206/202729176-8dc49254-0623-4fe8-8cfd-4f90d831386f.png">

**Comment by hou27** [comment]
> @hou27 변경했는데 https->http라 요청 에러 발생하네요.. 혹시 https로 변경 가능하신가요!? <img alt="스크린샷 2022-11-18 오후 11 33 28" width="550" src="https://user-images.githubusercontent.com/73734206/202729176-8dc49254-0623-4fe8-8cfd-4f90d831386f.png">

넵

**Comment by hou27** [comment]
@oseunghyun 
https://test.hou27.shop/
이 주소로 올렸습니다!

**Comment by oseunghyun** [comment]
@hou27 정호님 404로 뜨는데 확인해주실 수 있을까요?

<img width="388" alt="스크린샷 2022-11-19 오전 10 29 36" src="https://user-images.githubusercontent.com/73734206/202827657-6b3ab8bc-03b0-44d4-b7f5-4cd459e05cfd.png">
<img width="1388" alt="스크린샷 2022-11-19 오전 10 29 29" src="https://user-images.githubusercontent.com/73734206/202827660-1b864b6b-3a7c-4f0e-8b93-31d743d6754a.png">

**Comment by hou27** [comment]
> @hou27 정호님 404로 뜨는데 확인해주실 수 있을까요?
> 
> <img alt="스크린샷 2022-11-19 오전 10 29 36" width="388" src="https://user-images.githubusercontent.com/73734206/202827657-6b3ab8bc-03b0-44d4-b7f5-4cd459e05cfd.png">
> 
> <img alt="스크린샷 2022-11-19 오전 10 29 29" width="1388" src="https://user-images.githubusercontent.com/73734206/202827660-1b864b6b-3a7c-4f0e-8b93-31d743d6754a.png">

https://test.hou27.shop/auth/login 를

https://test.hou27.shop/api/auth/login 로 시도해보시면 될 것 같아요!
오타나신 것 같네요 ㅎㅎ

**Comment by oseunghyun** [comment]
@hou27 앗......그러네요🙀감사합니다ㅎㅎㅎㅎㅎ

**Comment by hou27** [comment]
변경된 테스트용 프론트 주소 반영 완료
https://quickchive.netlify.app/
