### ISSUE TITLE
조회 시 시간 정보가 다르게 읽히는 오류

### ISSUE THREAD

**Issue by hou27** [Quickchive/quickchive-backend#132]
@hou27
콘텐츠 저장과 수정시에 설정한 읽을 기한과
조회했을 때의 읽을 기한이 1일 차이가 납니다

_Originally posted by @oseunghyun in https://github.com/Quickchive/quickchive-backend/issues/131#issuecomment-1334911983_

**Comment by hou27** [comment]
api server의 timezone을 Asia/Seoul로 변경하면서 GMT+0인 DB server와의 timezone 차이 때문에 발생하던 문제

**Comment by hou27** [comment]
UTC 포맷으로 시간이 반환되고 있었을 뿐 저장한 시간과 차이는 없었던 것으로 확인됨.

**Comment by oseunghyun** [comment]
@hou27 아하아하 그런부분이었군요 알겠습니다!!

**Comment by hou27** [comment]
> @hou27 아하아하 그런부분이었군요 알겠습니다!!

넵 감사합니다!

**Comment by oseunghyun** [comment]
@hou27  
수정 요청할 때의 deadline이랑 
<img width="514" alt="스크린샷 2022-12-03 오후 3 57 46" src="https://user-images.githubusercontent.com/73734206/205429130-ae02c7f4-6bc9-4d69-b005-d3d4889ac536.png">

조회할 때 응답받은 deadline 값 자체가 1일 차이
가 나는데 제가 임의로 가공해도 되는 부분인가요..? 
<img width="1264" alt="스크린샷 2022-12-03 오후 3 58 52" src="https://user-images.githubusercontent.com/73734206/205429144-46aca8b2-cda4-40d5-ab9c-d2f77a4de363.png">

**Comment by oseunghyun** [comment]
@hou27  아 정호님 위에 코멘트는 답 안 하셔도 돼요 이해했어요!!

**Comment by hou27** [comment]
> @hou27  아 정호님 위에 코멘트는 답 안 하셔도 돼요 이해했어요!!

넵!!
